name: CI/CD
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  FUNCTION_NAME: f3brand_stripe
  PROJECT_ID: f3brand-316617
  GCP_SA: stripe@f3brand-316617.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Functions
        run: >-
          gcloud functions deploy ${{ env.FUNCTION_NAME }}
          --entry-point=main
          --region=us-central1
          --timeout=530
          --project=${{ env.PROJECT_ID }}
          --memory=1024MB
          --runtime=python39
          --trigger-http
          --service-account=${{ env.GCP_SA }}
          --set-env-vars=API_KEY=${{ secrets.API_KEY }}
